//go:build ignore

// gendocs generates Markdown reference pages for all gwp commands
// into docs/commands/. Run via: go run cmd/gwp-gendocs/main.go
// or: make docs
package main

import (
	"log"
	"os"
	"path/filepath"

	"github.com/spf13/cobra/doc"

	"github.com/dio/gateway-pairs/internal/cli"
)

func main() {
	root := cli.BuildRoot(cli.BuildInfo{
		Version:   "dev",
		EGVersion: "dev",
	})
	// DisableAutoGenTag removes the "Auto generated by spf13/cobra" footer.
	root.DisableAutoGenTag = true

	outDir := filepath.Join("docs", "commands")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		log.Fatalf("mkdir %s: %v", outDir, err)
	}

	if err := doc.GenMarkdownTree(root, outDir); err != nil {
		log.Fatalf("GenMarkdownTree: %v", err)
	}
	log.Printf("wrote command docs to %s/", outDir)
}
