package assets

import (
	"embed"
	"io/fs"
)

// Charts holds the eg-crds and eg-pair Helm chart trees.
// Content is copied from charts/ by 'make generate-assets'.
//
//go:embed charts
var charts embed.FS

// CRDs holds pre-rendered CRD YAML generated by 'make generate-crds'.
// Files are NOT committed; they are generated at build time.
// The directory is created empty by generate-crds if it does not exist,
// so the embed directive always resolves even on a clean checkout.
//
//go:embed crds
var crds embed.FS

// Charts returns the embedded chart filesystem rooted at "charts/".
func Charts() fs.FS {
	sub, err := fs.Sub(charts, "charts")
	if err != nil {
		panic("embedded charts missing: " + err.Error())
	}
	return sub
}

// CRDs returns the embedded CRD filesystem rooted at "crds/".
func CRDs() fs.FS {
	sub, err := fs.Sub(crds, "crds")
	if err != nil {
		panic("embedded crds missing: " + err.Error())
	}
	return sub
}
