// Package charts embeds the eg-crds and eg-pair Helm chart trees and the
// pre-rendered CRD YAML files generated by 'make generate-crds'.
//
// Layout after 'make generate-crds':
//
//   charts/
//     eg-crds/     Helm chart source (committed)
//     eg-pair/     Helm chart source (committed)
//     crds/
//       .gitkeep                       committed -- keeps dir present on clean checkout
//       gateway-api-standard.yaml      generated, gitignored
//       gateway-api-experimental.yaml  generated, gitignored
//       envoy-gateway.yaml             generated, gitignored
//
// On a clean checkout only .gitkeep is present; the *.yaml files are absent.
// The CLI detects this at runtime and prints a clear error if CRD install
// is attempted without the generated files.
package charts

import (
	"embed"
	"io/fs"
)

//go:embed eg-pair all:crds
var fs_ embed.FS

// FS returns the full embedded filesystem (charts + crds subdirectory).
func FS() fs.FS { return fs_ }

// Charts returns a filesystem rooted at the chart trees.
// Accessible as eg-crds/... and eg-pair/...
func Charts() fs.FS { return fs_ }

// CRDs returns a filesystem rooted at charts/crds/.
// Files: gateway-api-standard.yaml, gateway-api-experimental.yaml, envoy-gateway.yaml
// Returns an empty-ish FS (only .gitkeep) on a clean checkout.
func CRDs() fs.FS {
	sub, err := fs.Sub(fs_, "crds")
	if err != nil {
		panic("embedded crds missing: " + err.Error())
	}
	return sub
}
