{{- $sysNS := include "eg-pair.systemNamespace" . }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-gateway-config
  namespace: {{ $sysNS }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    eg-pair: {{ .Values.pair.index | quote }}
data:
  envoy-gateway.yaml: |
    apiVersion: gateway.envoyproxy.io/v1alpha1
    kind: EnvoyGateway
    gateway:
      controllerName: gateway.envoyproxy.io/{{ include "eg-pair.gatewayClassName" . }}
    provider:
      type: Kubernetes
      kubernetes:
        deploy:
          type: GatewayNamespace
        watch:
          type: Namespaces
          namespaces:
          - {{ $sysNS }}
          - {{ include "eg-pair.dataplaneNamespace" . }}
    extensionApis:
      enableEnvoyPatchPolicy: true
