{{- if .Values.envoyProxy.create }}
{{- $dpNS := include "eg-pair.dataplaneNamespace" . }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: {{ .Values.envoyProxy.name }}
  namespace: {{ $dpNS }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    eg-pair: {{ .Values.pair.index | quote }}
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        pod:
          labels:
            eg-pair: {{ .Values.pair.index | quote }}
      envoyService:
        type: ClusterIP
{{- end }}
