{{- $sysNS := include "eg-pair.systemNamespace" . }}
{{- $gcName := include "eg-pair.gatewayClassName" . }}

apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ $gcName }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    eg-pair: {{ .Values.pair.index | quote }}
spec:
  controllerName: gateway.envoyproxy.io/{{ include "eg-pair.gatewayClassName" . }}
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: eg
    namespace: {{ $sysNS }}
