{{- $gcName := include "eg-pair.gatewayClassName" . }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ $gcName }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    eg-pair: {{ .Values.pair.index | quote }}
spec:
  controllerName: gateway.envoyproxy.io/{{ $gcName }}
  {{- if .Values.envoyProxy.create }}
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: {{ .Values.envoyProxy.name }}
    namespace: {{ include "eg-pair.dataplaneNamespace" . }}
  {{- end }}
