{{- $sysNS := include "eg-pair.systemNamespace" . }}

# xDS server + metrics -- accessed by Envoy proxy pods from the dataplane namespace.
apiVersion: v1
kind: Service
metadata:
  name: envoy-gateway
  namespace: {{ $sysNS }}
  labels:
    app.kubernetes.io/name: envoy-gateway
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    eg-pair: {{ .Values.pair.index | quote }}
spec:
  selector:
    app.kubernetes.io/name: envoy-gateway
    eg-pair: {{ .Values.pair.index | quote }}
  ports:
  - name: grpc
    port: 18000
    targetPort: grpc
    protocol: TCP
  - name: ratelimit
    port: 18001
    targetPort: ratelimit
    protocol: TCP
  - name: metrics
    port: 19001
    targetPort: metrics
    protocol: TCP
