apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy-gateway
  namespace: {{ include "eg-pair.systemNamespace" . }}
  labels:
    app.kubernetes.io/name: envoy-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    eg-pair: {{ .Values.pair.index | quote }}
