apiVersion: v1
kind: ConfigMap
metadata:
  name: eg-crds-version
  namespace: kube-system
  labels:
    app.kubernetes.io/name: eg-crds
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  chart-version: {{ .Chart.Version | quote }}
  app-version: {{ .Chart.AppVersion | quote }}
  gatewayAPI-enabled: {{ .Values.crds.gatewayAPI.enabled | quote }}
  gatewayAPI-channel: {{ .Values.crds.gatewayAPI.channel | quote }}
  envoyGateway-enabled: {{ .Values.crds.envoyGateway.enabled | quote }}
